[ {
	head : {
		textItems : [],
		listItems : [
				{
					"column" : "",
					"displayOrder" : "1",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "v30_md_customer.name",
					"linkFieldName" : "客户名称",
					"linkModuleCode" : "v30_md_customer",
					"linkModuleName" : "客户表",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order.v30_md_customer_code",
					"metadataModuleCode" : "v30_bd_order",
					"metadataModuleName" : "订单退货表",
					"name" : "客户code",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "客户code",
					"whereClause" : "v30_bd_order.v30_md_customer_code=v30_md_customer.code and "
				},
				{
					"column" : "",
					"displayOrder" : "2",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "v30_md_organization.name",
					"linkFieldName" : "员工姓名\\部门名称",
					"linkModuleCode" : "v30_md_organization",
					"linkModuleName" : "人员/部门表",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order.v30_md_organization_code",
					"metadataModuleCode" : "v30_bd_order",
					"metadataModuleName" : "订单退货表",
					"name" : "人员-部门code",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "员工姓名",
					"whereClause" : ""
				},
				{
					"column" : "",
					"displayOrder" : "3",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "",
					"linkFieldName" : " ",
					"linkModuleCode" : "",
					"linkModuleName" : " ",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order.delivery_date",
					"metadataModuleCode" : "v30_bd_order",
					"metadataModuleName" : "订单退货表",
					"name" : "要求送货时间",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "送货时间",
					"whereClause" : ""
				},
				{
					"column" : "",
					"displayOrder" : "4",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "v30_md_product.name",
					"linkFieldName" : "产品名称",
					"linkModuleCode" : "v30_md_product",
					"linkModuleName" : "产品表",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order_dl.v30_md_product_code",
					"metadataModuleCode" : "v30_bd_order_dl",
					"metadataModuleName" : "订单退货详情表",
					"name" : "产品code",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "单品名称",
					"whereClause" : ""
				},
				{
					"column" : "",
					"displayOrder" : "5",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "",
					"linkFieldName" : " ",
					"linkModuleCode" : "",
					"linkModuleName" : " ",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order_dl.goods_count",
					"metadataModuleCode" : "v30_bd_order_dl",
					"metadataModuleName" : "订单退货详情表",
					"name" : "订货数量",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "订货数量",
					"whereClause" : ""
				},
				{
					"column" : "",
					"displayOrder" : "6",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "v30_md_product.name",
					"linkFieldName" : "产品名称",
					"linkModuleCode" : "v30_md_product",
					"linkModuleName" : "产品表",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order_dl.v30_md_product_gift_code",
					"metadataModuleCode" : "v30_bd_order_dl",
					"metadataModuleName" : "订单退货详情表",
					"name" : "赠品code",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "赠品名称",
					"whereClause" : ""
				}, {
					"column" : "",
					"displayOrder" : "7",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "",
					"linkFieldName" : " ",
					"linkModuleCode" : "",
					"linkModuleName" : " ",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order_dl.gift_count",
					"metadataModuleCode" : "v30_bd_order_dl",
					"metadataModuleName" : "订单退货详情表",
					"name" : "赠品数量",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "赠品数量",
					"whereClause" : ""
				}, {
					"column" : "",
					"displayOrder" : "8",
					"fieldDesc" : "",
					"fieldType" : "popupListFix",
					"isNewExtField" : false,
					"iseditable" : "否",
					"issearchable" : "否",
					"linkFieldCode" : "",
					"linkFieldName" : " ",
					"linkModuleCode" : "",
					"linkModuleName" : " ",
					"linkPopupPageCode" : "",
					"linkPopupPageName" : "",
					"metadataColumnCode" : "v30_bd_order_dl.amount",
					"metadataModuleCode" : "v30_bd_order_dl",
					"metadataModuleName" : "订单退货详情表",
					"name" : "金额",
					"newExtField" : "",
					"showLinkPopupText" : "",
					"text" : "金额",
					"whereClause" : ""
				} ],
		photoItems : []
	},
	data : {
		textItems : [],
		listItems : [ {
			"CELL0" : "永吉路乐家福菜场68摊位",
			"CELL1" : "程金伟",
			"CELL2" : null,
			"V30_BD_ORDER_ID" : "6545225",
			"CELL3" : "乔什五香榨菜",
			"CELL4" : "10",
			"V30_BD_ORDER_DL_ID" : "5447206",
			"CELL5" : "乔什五香榨菜",
			"CELL6" : "1",
			"CELL7" : null
		}, {
			"CELL0" : "永吉路乐家福菜场68摊位",
			"CELL1" : "程金伟",
			"CELL2" : null,
			"V30_BD_ORDER_ID" : "6545225",
			"CELL3" : "达福琪脆瓜丁",
			"CELL4" : "1",
			"V30_BD_ORDER_DL_ID" : "5447209",
			"CELL5" : null,
			"CELL6" : null,
			"CELL7" : null
		}, {
			"CELL0" : "永吉路乐家福菜场68摊位",
			"CELL1" : "程金伟",
			"CELL2" : null,
			"V30_BD_ORDER_ID" : "6545225",
			"CELL3" : "达福琪餐餐香",
			"CELL4" : "1",
			"V30_BD_ORDER_DL_ID" : "5447208",
			"CELL5" : null,
			"CELL6" : null,
			"CELL7" : null
		}, {
			"CELL0" : "永吉路乐家福菜场68摊位",
			"CELL1" : "程金伟",
			"CELL2" : null,
			"V30_BD_ORDER_ID" : "6545225",
			"CELL3" : "达福琪红油笋丝（达）",
			"CELL4" : "1",
			"V30_BD_ORDER_DL_ID" : "5447207",
			"CELL5" : null,
			"CELL6" : null,
			"CELL7" : null
		} ],
		photoItems : []
	}
} ]